---
permalink: recover/recovery-deployment.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereのセットアップを失ったあとにONTAPが動作している場合は、ONTAPを使用してONTAP tools for VMware vSphereのセットアップをリカバリできます。セットアップが失われたら、セットアップを正常に停止してください。 
---
= ONTAP Tools for VMware vSphereセットアップのリカバリ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereのセットアップを失った場合は、ONTAPボリュームのデータに含まれているデータを使用してONTAP tools for VMware vSphereのセットアップをリカバリできます。セットアップが失われたら、セットアップを正常に停止してください。


NOTE: vCenter ServerまたはONTAPデータ管理ソフトウェアで問題があると、ONTAP tools for VMware vSphereのセットアップをリカバリできません。

* 手順 *

. vSphereサーバにログインします。
. 作成したリソースプール、またはOVAを導入するノードクラスタまたはホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF Template]*を選択します。
. OVAファイルを_.ova_fileのURLから選択するか、または_.ova_fileが保存されているフォルダを参照して、*[次へ]*をクリックします。
+

NOTE: リカバリセットアップのインストールに使用したのと同じOVAビルドを使用する必要があります。

. 仮想マシンの名前とフォルダを選択し、*[Next]*を選択します。
. ホストを選択し、*[次へ]*を選択します。
. テンプレートの概要を確認し、* Next *を選択します。
. ライセンス契約を読んで同意し、* Next *を選択します。
. [設定]ウィンドウで、*[リカバリ]*オプションを選択します。
. [ストレージの選択]*ウィンドウで、構成ファイルとディスクファイルのストレージを選択します。
. [ネットワークの選択]ウィンドウで、各ソースネットワークの宛先ネットワークを選択します。
+

NOTE: ロードバランサのIPアドレスとKubernetes APIサーバのIPアドレスは保持する必要があります。ノードのIPアドレスを変更することも、同じIPアドレスを維持することもできます。

. [テンプレートのカスタマイズ]ウィンドウで、必要な詳細を入力し、*[次へ]*をクリックします。
+

NOTE: SVMスコープを有効にした場合は、管理IPアドレスでのSVMサポートをすでに有効にしておく必要があります。

. [選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。
+
導入タスクが作成されると、進行状況がvSphereタスクバーに表示されます。

. タスクが完了したら、VMの電源をオンにします。
+
インストールが開始されます。インストールの進行状況は、VMのWebコンソールで追跡できます。インストールの一環として、ノード構成が検証されます。OVFフォームの[Customize template]の下のさまざまなセクションで入力された内容が検証されます。不一致がある場合は、修正措置を講じるように求めるダイアログが表示されます。

. ダイアログプロンプトで必要な変更を行います。Tabボタンを使用してパネルを移動し、* OK *を選択します。
+
指定した値が再度検証されます。ONTAP tools for VMware vSphereでは、無効な値を3回修正できます。3回試行しても問題を修正できない場合は、製品のインストールが停止し、新しいVMでインストールを試すことを推奨します。



インストールが完了すると、WebコンソールにONTAP tools for VMware vSphereの状態が表示されます。

インストールが完了したら、ページのガイドラインに従ってハードウェア要件を手動で編集する必要があります link:../deploy/prerequisites.html["ONTAP Tools for VMware vSphereを導入するための前提条件"] 。
