---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: 非HAシングルノードは、小規模構成または中規模構成で構成できます。 
---
= ONTAP Tools for VMware vSphereの導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools for VMware vSphereは、次の2つの構成で導入できます。

* ヒHAノシングルノードコウセイ
* HA構成


[role="tabbed-block"]
====
.ヒHAノシングルノードコウセイ
--
非HAのシングルノード構成は、小規模または中規模構成に導入できます。

* 小規模な非HA構成には、8個のCPUと16GBのRAMが搭載されています。
* 中規模の非HA構成には、12個のCPUと24GBのRAMが搭載されています。


* 始める前に *

ネットワークルートが存在することを確認します。ストレージデータネットワークにVM管理ネットワークからアクセスできる必要があります。たとえば、ONTAPにログインし、command_network route create -vserver <SVM>-destination 0.0.0.0/0 -gateway <gateway_ip>_を実行します。

* 手順 *

.  `.zip`バイナリ（_.ova_）とONTAP tools for VMware vSphereの署名済み証明書を含むファイルをからダウンロードします https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetAppサポートサイト"^]。
. vSphereサーバにログインします。
. 作成したリソースプール、またはクラスタまたはOVAを導入するホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF template...]*を選択します。
+

NOTE: 管理対象のVVOLデータストアには、ONTAP Tools for VMware vSphere仮想マシンを導入しないでください。

. OVAファイルを_.ova_fileのURLから選択するか、または_.ova_fileが保存されているフォルダを参照して、*[次へ]*をクリックします。
. コンピュータリソースを選択し、* Next *をクリックします。
. テンプレートの詳細を確認し、*[次へ]*をクリックします。
. ライセンス契約を読んで同意します。
. 導入構成を選択し、*[次へ]*をクリックします。
+
高度な導入オプションでは、ONTAPでボリュームを作成するための動的ストレージプロビジョニングツールとしてTridentを使用し、簡単な導入ではローカルストレージを使用してボリュームを作成します。

. 構成用のストレージとディスクファイルを選択し、*[次へ]*をクリックします。
. 各ソースネットワークのデスティネーションネットワークを選択し、*[次へ]*をクリックします。
. [テンプレートのカスタマイズ]*で必要な詳細を入力し、*[次へ]*をクリックします。
+
** SVMスコープを有効にした場合は、管理IPアドレスでのSVMサポートをすでに有効にしておく必要があります。
** ここで提供される情報は、インストールプロセス中に適切なパターンがあるかどうか検証されます。不一致がある場合は、Webコンソールにエラーメッセージが表示され、誤った情報を修正するように求められます。
** ホスト名には、大文字（A ~ Z）、小文字（a ~ z）、数字（0 ~ 9）、または特殊文字ハイフン（-）を使用する必要があります。デュアルスタックを設定する場合は、IPv6アドレスにマッピングされたホスト名を指定します。
+

NOTE: Pure IPv6はサポートされていません。mixedモードは、IPv6とIPv4の両方のアドレスを持つVLANでサポートされます。



. [選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。
+
導入タスクが作成されると、進行状況がvSphereタスクバーに表示されます。

. タスクが完了したら、VMの電源をオンにします。


--
.HA構成
--
HA 3ノードは、小規模、中規模、大規模のいずれかの構成で構成できます。HA環境では、Tridentを使用してサービスデータを格納します。

* 小規模なHA 3ノードには、ノードあたり8個のCPUと16GBのRAMが搭載されています。
* 中規模HA 3つのノードには、ノードあたり12個のCPUと24GBのRAMが搭載されています。
* 大規模なHA 3ノードには、ノードあたり16個のCPUと32GBのRAMが搭載されています。


* 始める前に *

このタスクでは、小規模、中規模、または高可用性構成にHA 3ノードを設置する手順を説明します。

HA 3ノード構成を導入するには、コンテンツライブラリの作成が必須の前提条件となります。VMwareのコンテンツライブラリは、VMテンプレート、vAppテンプレート、およびその他の種類のファイルを格納するコンテナオブジェクトです。コンテンツライブラリを使用した展開では、ネットワーク接続に依存しないシームレスなエクスペリエンスが提供されます。


NOTE: コンテンツライブラリは、クラスタ内のすべてのホストがアクセスできるように、共有データストアに格納します。HA構成にOVAを導入する前に、OVAを格納するコンテンツライブラリを作成する必要があります。


NOTE: アップロードしたコンテンツライブラリテンプレートは、再起動時に使用されるため、展開後に削除しないでください。

次の手順に従ってコンテンツライブラリを作成します。

.  `.zip`バイナリ（_.ova_）とONTAP tools for VMware vSphereの署名済み証明書を含むファイルをからダウンロードします https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetAppサポートサイト"^]。
. 次のコマンドを使用してvSphere Clientにログインします。 `\https://vcenterip/ui`
. vSphere Clientの横の省略記号を選択し、*[Content library]*を選択します。
. ページの右側にある*[作成]*を選択します。
. ライブラリの名前を指定し、コンテンツライブラリを作成します。
. 作成したコンテンツライブラリに移動します。
. ページの右側の*[Actions]*を選択し、*[Import item]*を選択してOVAファイルをインポートします。



NOTE: 詳細については https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["コンテンツライブラリの作成と使用"]、ブログを参照してください。

OVAがコンテンツライブラリにインポートされていることを確認します。コンテンツライブラリの名前と、OVAアイテムに付けたライブラリアイテムの名前を手元に置いておきます。


NOTE: 導入を進める前に、ONTAPツールのインストール中に、インベントリ上のクラスタのDistributed Resource Scheduler（DRS）を「保守的」に設定してください。これにより、インストール中にVMが移行されなくなります。

* 手順 *

.  `.zip`バイナリ（_.ova_）とONTAP tools for VMware vSphereの署名済み証明書を含むファイルをからダウンロードします https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetAppサポートサイト"^]。
. vSphereサーバにログインします。
. 作成したリソースプール、またはクラスタまたはOVAを導入するホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF template...]*を選択します。
+

NOTE: 管理対象のVVOLデータストアには、ONTAP Tools for VMware vSphere仮想マシンを導入しないでください。

. OVAファイルを_.ova_fileのURLから選択するか、または_.ova_fileが保存されているフォルダを参照して、*[次へ]*をクリックします。
. コンテンツライブラリからONTAP Tools for VMware vSphereを導入するには、次の手順を実行します。
+
.. コンテンツライブラリに移動し、展開するライブラリアイテムをクリックします。
.. [Actions]*>*[New VM from this template]*をクリックします。


. コンピュータリソースを選択し、* Next *をクリックします。
. テンプレートの詳細を確認し、*[次へ]*をクリックします。
. ライセンス契約を読んで同意し、*[Next]*をクリックします。
. 導入構成を選択し、*[次へ]*をクリックします。
. 構成用のストレージとディスクファイルを選択し、*[次へ]*をクリックします。
. 各ソースネットワークのデスティネーションネットワークを選択し、*[次へ]*をクリックします。
. [テンプレートのカスタマイズ]ウィンドウで、必要なフィールドに入力し、*[次へ]*をクリックします。
+
** HAモードの導入環境では、導入後にVM名を変更しないでください。
** SVMスコープを有効にした場合は、管理IPアドレスでのSVMサポートをすでに有効にしておく必要があります。
** ここで提供される情報は、インストールプロセス中に適切なパターンがあるかどうか検証されます。不一致がある場合は、Webコンソールにエラーメッセージが表示され、誤った情報を修正するように求められます。
** ホスト名には、大文字（A ~ Z）、小文字（a ~ z）、数字（0 ~ 9）、または特殊文字ハイフン（-）を使用する必要があります。デュアルスタックを設定する場合は、IPv6アドレスにマッピングされたホスト名を指定します。
+

NOTE: Pure IPv6はサポートされていません。mixedモードは、IPv6とIPv4の両方のアドレスを持つVLANでサポートされます。



. [選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。
+
導入タスクが作成されると、進行状況がvSphereタスクバーに表示されます。

. タスクが完了したら、VMの電源をオンにします。


--
====
インストールの進行状況は、VMのWebコンソールで追跡できます。

OVFフォームに入力した値に不一致がある場合は、修正措置を講じるように求めるダイアログボックスが表示されます。ダイアログボックス内で必要な変更を行い、タブボタンを使用してナビゲートして「OK」を選択します。問題の修正は3回試行できます。3回試行しても問題が解決しない場合は、インストールプロセスが中止されるため、新しいVMでインストールを再試行することを推奨します。
