---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。 
---
= 保護グループの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。

* 必要なもの *

ソースサイトとターゲットサイトの両方が次のように構成されていることを確認する必要があります。

* 同じバージョンのVMware Live Site Recoveryがインストールされている
* 仮想マシン
* 保護対象サイトとリカバリサイトをペアリング
* ソースとデスティネーションのデータストアがそれぞれのサイトにマウントされていること


* 手順 *

. vCenter Serverにログインし、*[サイトリカバリ]*>*[保護グループ]*をクリックします。
. [* 保護グループ * ] ウィンドウ枠で、 [ * 新規 * ] をクリックします。
. 保護グループの名前と説明、方向を指定し、*次へ*をクリックします。
. [タイプ]*フィールドで、NFSおよびVMFSデータストアの[タイプ]フィールドオプション...*を[データストアグループ（アレイベースのレプリケーション）]として選択します。フォールトドメインは、レプリケーションが有効になっているSVMにすぎません。ピアリングのみが実装されていて問題がないSVMが表示されます。
. [レプリケーショングループ]タブで、有効なアレイペアまたは設定した仮想マシンがあるレプリケーショングループのいずれかを選択し、*[次へ]*をクリックします。
+
レプリケーショングループ上のすべての仮想マシンが保護グループに追加されます。

. 既存のリカバリプランを選択するか、または新しいリカバリプランに追加 * をクリックして新しいプランを作成します。
. [ 完了準備完了 ] タブで、作成した保護グループの詳細を確認し、 [ 完了 ] をクリックします。

