---
permalink: concepts/key-points-about-assign-and-modify-permissions.html 
sidebar: sidebar 
keywords:  
summary: vCenter Serverのアクセス許可を使用する場合は、いくつかの重要な点に注意する必要があります。ONTAP tools for VMware vSphereのタスクを実行できるかどうかは、アクセス許可を割り当てた場所や、アクセス許可の変更後にユーザが実行した操作によって異なります。 
---
= vCenter Serverの権限の割り当てと変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Serverのアクセス許可を使用する場合は、いくつかの重要な点に注意する必要があります。ONTAP tools for VMware vSphereのタスクを実行できるかどうかは、アクセス許可を割り当てた場所や、アクセス許可の変更後にユーザが実行した操作によって異なります。



== 権限の割り当て

vCenter Serverのアクセス許可は、vSphereのオブジェクトおよびタスクへのアクセスを制限する場合にのみ設定します。それ以外の場合は、管理者としてログインできます。このログインにより、すべてのvSphereオブジェクトに自動的にアクセスできるようになります。

権限の割り当て先によって、ユーザが実行できるONTAP tools for VMware vSphereタスクが決まります。

場合によっては、タスクを確実に完了させるために、ルートオブジェクトなどの上位レベルに権限を割り当てる必要があります。これは、特定のvSphereオブジェクトには適用されない権限（タスクの追跡など）がタスクに必要な場合や、必要な権限がvSphere以外のオブジェクト（ストレージシステムなど）に適用される場合に該当します。

このような場合は、子エンティティに継承されるようにアクセス許可を設定できます。子エンティティに他の権限を割り当てることもできます。子エンティティに割り当てたアクセス許可は、親エンティティから継承されたアクセス許可を上書きします。つまり、子エンティティにアクセス許可を付与して、ルートオブジェクトに割り当てられ、子エンティティに継承されるアクセス許可の範囲を制限できます。


TIP: 会社のセキュリティポリシーでアクセス許可の制限が厳しい場合を除き、ルートオブジェクト（ルートフォルダとも呼ばれます）にアクセス許可を割り当てることをお勧めします。



== アクセス許可と非vSphereオブジェクト

作成したアクセス許可はvSphere以外のオブジェクトに適用されます。たとえば、ストレージシステムはvSphereオブジェクトではありません。ストレージシステムの環境権限がある場合は、tools for VMware vSphereルートオブジェクトに割り当てることができるvSphereオブジェクトがないため、その権限を含むアクセス許可をONTAP tools for VMware vSphereルートオブジェクトに割り当てる必要があります。

たとえば、ONTAP tools for VMware vSphereの「Add/Modify/Skip storage systems」などの権限を含むすべてのアクセス許可は、ルートオブジェクトレベルに割り当てる必要があります。



== アクセス許可の変更

変更できる権限は一度に1つです。

アクセス許可に含まれる権限が変更された場合、そのアクセス許可が関連付けられたユーザは、更新されたアクセス許可を有効にするためにログアウトしてログインし直す必要があります。
