---
permalink: concepts/privileges-required.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools for VMware vSphereのタスクごとに、ONTAP Tools for VMware vSphere固有の権限とvCenter Server標準の権限の組み合わせが異なります。 
---
= ONTAP Tools for VMware vSphereのタスクに必要な権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools for VMware vSphereのタスクごとに、ONTAP Tools for VMware vSphere固有の権限とvCenter Server標準の権限の組み合わせが異なります。

ONTAP tools for VMware vSphere GUIにアクセスするには、製品レベルのONTAP tools固有のView権限が、適切なvSphereオブジェクトレベルで割り当てられている必要があります。この権限なしでログインすると、NetAppアイコンをクリックしたときにONTAP tools for VMware vSphereにエラーメッセージが表示され、ONTAP toolsにアクセスできません。

View *権限では、VMware vSphere用のONTAPツールにアクセスできます。この権限では、ONTAP tools for VMware vSphere内でタスクを実行することはできません。ONTAP tools for VMware vSphereのタスクを実行するには、タスクに対する適切なONTAP tools固有の権限とvCenter Server標準の権限が必要です。

割り当てレベルによって、UIのどの部分を表示できるかが決まります。ルートオブジェクト（フォルダ）にView権限を割り当てると、NetAppアイコンをクリックしてONTAP tools for VMware vSphereにアクセスできるようになります。

別のvSphereオブジェクトレベルにView権限を割り当てることもできますが、その場合、表示および使用できるONTAP Tools for VMware vSphereメニューが制限されます。

View権限を含むアクセス許可は、ルートオブジェクトに割り当てることを推奨します。
