---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereは、NetAppストレージシステムに最適なESXiホストのマルチパス設定とHBAタイムアウト設定を確認して設定します。 
---
= ESXiサーバのマルチパスとタイムアウトの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereは、NetAppストレージシステムに最適なESXiホストのマルチパス設定とHBAタイムアウト設定を確認して設定します。

* このタスクについて *

構成やシステムの負荷によっては、このプロセスに時間がかかることがあります。タスクの進行状況は、[最近のタスク]パネルに表示されます。タスクが完了すると、ホストのステータスを示す[アラート]アイコンが[正常]アイコンまたは[リブートを保留中]アイコンに変わります。

* 手順 *

. VMware vSphere Web Clientの[ホーム]ページで、*[ホストおよびクラスタ]*をクリックします。
. ホストを右クリックし、* NetApp ONTAP tools *>* Update host data *を選択します。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *をクリックします。
. ONTAP tools for VMware vSphereプラグインの概要（ダッシュボード）で、ESXiホストコンプライアンスカードに移動します。
. [推奨設定の適用]*リンクを選択します。
. [推奨されるホスト設定を適用]*ウィンドウで、NetAppの推奨されるホスト設定に準拠するホストを選択し、*[次へ]*をクリックします。
+

NOTE: ESXiホストを展開すると、現在の値を確認できます。

. 設定ページで、必要に応じて推奨値を選択します。
. 概要ペインで値を確認し、*[完了]*をクリックします。進捗状況は、[最近使用したタスク]パネルで追跡できます。

