---
permalink: manage/igroup-management.html 
sidebar: sidebar 
keywords:  
summary: ONTAPでは、エクスポートポリシーを使用してホストへのボリュームデータパスにアクセスし、igroupを使用してESXiホストへのLUNデータパスにアクセスします。 
---
= igroupとエクスポートポリシーを管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPでは、エクスポートポリシーを使用してホストへのボリュームデータパスにアクセスし、イニシエータグループ（igroup）を使用してESXiホストへの論理ユニット番号（LUN）データパスにアクセスします。VMware vSphere向けのONTAPツールを使用すると、igroupを簡単かつわかりやすく作成でき、充実したエンドツーエンドのワークフローが提供されます。整合性を確保するために、ストレージプラットフォームでigroupを直接作成することはサポートされていません。

仮想ボリュームデータストアを作成またはvCenter Serverのホストにマウントする際には、データストアのプロトコルタイプに応じて、ホストにボリューム（NFS）またはLUN（iSCSI）へのアクセスを許可する必要があります。

エクスポートポリシーは動的に作成され、新しいエクスポートポリシーはtrident-uuidという名前形式で作成されます。ONTAPシステムマネージャで、*[ストレージ]*>*[Storage VM]*>*[ストレージVM名]*>*[設定]*>*[エクスポートポリシー]*の順に選択し、エクスポートポリシーを確認します。

ONTAP tools for VMware vSphereのigroupとエクスポートポリシーは効率的に管理され、次のようなメリットがあります。

* 移行されたエクスポートポリシーとigroupをサポートします。
* 仮想マシンの入出力処理が中断されることはありません。
* 手動操作なしで追加ホストへのマウントをサポートします。
* igroupとエクスポートポリシーの数を最小限に抑えることができます。
* ガベージコレクタは、未使用の管理対象igroupとエクスポートポリシーをすべて定期的に自動的に削除します。
* データストアがホストクラスタレベルでプロビジョニングされている場合は、igroupに追加されたホストクラスタの下にあるすべてのホストイニシエータを含むigroupが作成されます。

